CREATE TABLE Log (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Type TEXT NOT NULL,
    Name TEXT NOT NULL,
    World TEXT NOT NULL,
    Role TEXT NOT NULL,
    Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);